const projects = [
    {
      previewLink: 'http://www.previewLink.com',
      title: 'Buzzold',
      github: 'http://github.com',
      description: 'There are many things to consider when purchasing furniture for your home. One of the most important considerations is where you’ll want it placed and what kind will best suit both functions as well aesthetically? The AR app allows users not only to take photos with their phones but also to place 3D models into virtual spaces which can be viewed from all angles allowing them to see, how an item would look in any room or setting without actually having to buy it! Users have teamed up between this technology-powered design tool/shopping site combo so they may order online directly through its interface while viewing pictures before making purchase decisions – no more scrolling endlessly on YouTube, watch cat videos instead.',
      phone: '090832343243',
      myEmail: '',
      myGithub: '',
      myTwitter: '',
      myLinkedIn: '',
      fullName: 'Sanni Musa',
      userTitle: 'Backend Developer',
    },
    {
      previewLink: 'http://www.previewLink.com',
      title: 'GeezUp',
      github: 'http://github.com',
      description: 'Rather than going to a shop to get your documents to scan and then converting them into pdf. A scan and save it to pdf app can help you keep important records such as receipts, documents, report cards, notes, whiteboards etc., on your mobile securely. This app permits you to quickly scan your documents in high quality and store or send them as multipage PDF or JPEG files.',
      phone: '090832343243',
      myEmail: '',
      myGithub: '',
      myTwitter: '',
      myLinkedIn: '',
      fullName: 'Akin Musa',
      userTitle: 'Backend Developer',
    },
    {
    id: 1,
      previewLink: 'http://www.previewLink.com',
      title: 'LiteMint',
      github: 'http://github.com',
      description: 'This app checks your health day by day and suggests you proper meals that you should consume in order to remain healthy. It connects you to the numerous healthy-recipes that are provided by professional chef-bloggers. You can set your content to be provided as per your health situation, for e.g. if you are heart patient, you’ll be recommended recipes made of ingredients that are heart-healthy. The app can partner with groceries to deliver healthy items online directly from the app.',
      phone: '090832343243',
      myEmail: '',
      myGithub: '',
      myTwitter: '',
      myLinkedIn: '',
      fullName: 'Sunday Musa',
      userTitle: 'Backend Developer',
    },
    {
        id: 2,
      previewLink: 'http://www.previewLink.com',
      title: 'LintTod',
      github: 'http://github.com',
      description: 'The language learning app that helps users with some beginner lessons on different languages in one of the most brilliant app ideas for 2022. The app can have different levels of difficulty with the first level being alphabets and basic letters to the advanced level containing full-fledged conversations. The app can enable voice so the learners know how words are pronounced.',
      phone: '090832343243',
      myEmail: '',
      myGithub: '',
      myTwitter: '',
      myLinkedIn: '',
      fullName: 'Lukman Musa',
      userTitle: 'Blockchain Developer',
    },
    {
        id: 3,
      previewLink: 'http://www.previewLink.com',
      title: 'LawSlim',
      github: 'http://github.com',
      description: 'One of the primary concern of travelling abroad is not knowing the language of the country and the struggle of trying to communicate with the natives. An app that can translate your voice will be a revolutionary way to communicate for travellers. The words can be spoken to the phone which will be translated to their desired language. The app must also work both ways where other languages can be translated to your language in real-time.',
      phone: '090832343243',
      myEmail: '',
      myGithub: '',
      myTwitter: '',
      myLinkedIn: '',
      fullName: 'Yusuf Musa',
      userTitle: 'Frontend Developer',
    },
    {
        id: 4,
      previewLink: 'http://www.previewLink.com',
      title: 'FirstLane',
      github: 'http://github.com',
      description: 'There are many things to consider when purchasing furniture for your home. One of the most important considerations is where you’ll want it placed and what kind will best suit both functions as well aesthetically? The AR app allows users not only to take photos with their phones but also to place 3D models into virtual spaces which can be viewed from all angles allowing them to see, how an item would look in any room or setting without actually having to buy it! Users have teamed up between this technology-powered design tool/shopping site combo so they may order online directly through its interface while viewing pictures before making purchase decisions – no more scrolling endlessly on YouTube, watch cat videos instead.',
      phone: '090832343243',
      myEmail: '',
      myGithub: '',
      myTwitter: '',
      myLinkedIn: '',
      fullName: 'Aliu Olu',
      userTitle: 'Backend Developer',
    },
  ];

  export default projects;